[TSS]
TURRETS = [
  'PLACE YOUR TURRETS PUBLIC KEYT HERE', # self
  'GAMGW7ZESFF2KVGL7EMBBIAXTFAOF3MNI2JBWSPLTGMAKOSVLHDNZMA2', # EverLife.AI
  'GAATC6A7OOY7P36FTDFEHKHG7OS72A3NTSGM4RA6HJ5GKHUOEVRWGM76', # Script3
  'GARBNUK4IZDGKDJTIEWAL6FTY3UDRSRV275X4H5JS2PGCKTZZ3NDYU5U', # Litemint
  'GDZACR7XAJWU3JLJ5TVDOLCVB5DCIY2K7PHDR7ODGCEQTNVENOPHLCF7', # Atemosta
  'GA7FCNDCYS2N4XQER6P2KHK4FDVVM2PJCM3PODAZXC35QNJR5WINT6GO', # Zig3
  'GATCMFLSJYFQ3XVNMHXKWHVUYKGQ4FDRD6U7VXSDEIUDI7MVTK2SON5Q', # Ralphilius
]
