name = "tss-testnet-1"
type = "javascript"
usage_model = "bundled"
webpack_config = "webpack.config.js"
account_id = "3a30a140a42f91ff8ae70845e4b14cc1"
workers_dev = true

kv_namespaces = [
   { binding = "META", id = "18037a36900842078d2b98049287a1aa" },
   { binding = "TX_FUNCTIONS", id = "90a5e5555fa046d288a711d1addd1ee5" },
   { binding = "TX_FEES", id = "82a5a0eba1a6439fa3cc85556eccecd5" },
]
vars = { STELLAR_NETWORK = "TESTNET", HORIZON_URL = "https://horizon-testnet.stellar.org", TURRET_ADDRESS = "GAS3HIBJPTAHWS32Y3GRK5AMI4ALXWCAZQNUVVSYJJ43JBZGME4QJCBL", TURRET_RUN_URL = "https://h3uh4wzuoh.execute-api.us-east-1.amazonaws.com", TX_FUNCTION_FEE_DAYS_TTL = 180, XLM_FEE_MIN = 1, XLM_FEE_MAX = 10, UPLOAD_DIVISOR = 1000, RUN_DIVISOR = 100000 }

[build]
command = "npm i && npm run build"
[build.upload]
format = "modules"
main = "./shim.mjs"