name = "CHANGE ME"
type = "javascript"
usage_model = "bundled"
webpack_config = "webpack.config.js"
account_id = "Cloudflare Worker Account ID"
workers_dev = true

kv_namespaces = [
   { binding = "META", id = "ID From npx wrangler kv:namespace create 'META'" },
   { binding = "TX_FUNCTIONS", id = "ID from npx wrangler kv:namespace create TX_FUNCTIONS'" },
   { binding = "TX_FEES", id = "ID from npx wrangler kv:namespace create 'TX_FEES'" },
]
vars = { STELLAR_NETWORK = "TESTNET", HORIZON_URL = "https://horizon-testnet.stellar.org", TURRET_ADDRESS = "INSERT YOUR TURRET PUBLIC KEY", TURRET_RUN_URL = "INSERT RUNNER URL FROM SERVERLESS DEPLOYMENT", TX_FUNCTION_FEE_DAYS_TTL = 180, XLM_FEE_MIN = 1, XLM_FEE_MAX = 10, UPLOAD_DIVISOR = 1000, RUN_DIVISOR = 100000 }

[build]
command = "npm i && npm run build"
[build.upload]
format = "modules"
main = "./shim.mjs"
